name: Two Jobs Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  job_one:
    name: 🔧 Job One
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Running Job One"

  job_two:
    name: 🚀 Job Two
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Running Job Two"
